// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnodHoebiPh9bCAE3CXzST6VwydPQkDVs',
    appId: '1:668835293260:web:96aefc2e5815ec33deace9',
    messagingSenderId: '668835293260',
    projectId: 'my-app-flutter2023',
    authDomain: 'my-app-flutter2023.firebaseapp.com',
    storageBucket: 'my-app-flutter2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHMjmjcYDRA5GMvLNKP1joZzeB5E6JQhY',
    appId: '1:668835293260:android:6ac59368b9a18f70deace9',
    messagingSenderId: '668835293260',
    projectId: 'my-app-flutter2023',
    storageBucket: 'my-app-flutter2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNRhdz3Err4BPbqmNVvTXDKjDeAisxkXk',
    appId: '1:668835293260:ios:82e8840d8134c00adeace9',
    messagingSenderId: '668835293260',
    projectId: 'my-app-flutter2023',
    storageBucket: 'my-app-flutter2023.appspot.com',
    iosClientId: '668835293260-it3p2vq27fthh727ls6jllpmkmrs31f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNRhdz3Err4BPbqmNVvTXDKjDeAisxkXk',
    appId: '1:668835293260:ios:82e8840d8134c00adeace9',
    messagingSenderId: '668835293260',
    projectId: 'my-app-flutter2023',
    storageBucket: 'my-app-flutter2023.appspot.com',
    iosClientId: '668835293260-it3p2vq27fthh727ls6jllpmkmrs31f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );
}
